### ISSUE TITLE
High CPU demand

### ISSUE THREAD

**Issue by onurkose** [hawkeye64/app-extension-qplaceholder#1]
Hi,
I've been testing the extension on FF Dev. Ed. and Nightly and CPU demand never been lower than %35 with Nightly and %40+ Dev.Ed.
There was 10-15 extension component was on the screen.

**Comment by hawkeye64** [comment]
That would be because of the `animated` prop turned on. Turn it off and see what the difference is. Let me know. Thanks for the feedback. :heart:
